services:
  learnearnzone:
    build: .
    container_name: learnearnzone
    restart: always
    env_file: .env
    ports:       
      - "3000"
    networks:
      - global

networks:
  global:
    external: true
